
[functions.fuel-handler]
enabled = true
verify_jwt = false
import_map = "./functions/fuel-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fuel-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fuel-handler/*.html" ]

[functions.sync-weather-metrics]
enabled = true
verify_jwt = false
import_map = "./functions/sync-weather-metrics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-weather-metrics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-weather-metrics/*.html" ]

[functions.dispatch-aqi-weather-alerts]
enabled = true
verify_jwt = false
import_map = "./functions/dispatch-aqi-weather-alerts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispatch-aqi-weather-alerts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispatch-aqi-weather-alerts/*.html" ]

[functions.dispatch-fuel-alerts]
enabled = true
verify_jwt = false
import_map = "./functions/dispatch-fuel-alerts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispatch-fuel-alerts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispatch-fuel-alerts/*.html" ]

[functions.dispatch-stock-alerts]
enabled = true
verify_jwt = false
import_map = "./functions/dispatch-stock-alerts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispatch-stock-alerts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispatch-stock-alerts/*.html" ]
